# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20170331_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccine',
            field=models.ManyToManyField(blank=True, to='pet.Vaccine'),
        ),
    ]
